spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/blackjack
  r2dbc:
    url: r2dbc:mysql://mysql:3306/blackjack
    username: root
    password: rootpassword
  sql:
    init:
      mode: always
      schema-locations: classpath:blackjack.sql
logging:
  level:
    cat.itacademy.s05.t01.n01.BLACKJACK: DEBUG
